name: Test Apps
on:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        app:
          - bumptag
          - grade
    runs-on: macos-latest
    steps:
      - name: Install app
        run: brew install sv-tools/apps/${{ matrix.app }}
